// Generates docs/rules/table.md, the table of every registered rule with its category, default
// severity, confidence, frameworks and engine. It is included in docs/rules/index.md, so the
// published rules page always shows the severity policy as implemented in the registry.
//
// Run `npm run rules:table` after adding a rule or changing its metadata. tests/rules-table.test.ts
// fails when the generated file is stale.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RULE_CATEGORIES } from "../src/plugin/define-rule.js";
import type { RuleMeta } from "../src/plugin/define-rule.js";
import { RULE_REGISTRY, getCanonicalRuleId } from "../src/plugin/registry.js";

const packageDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const RULES_TABLE_PATH = path.resolve(packageDirectory, "../../docs/rules/table.md");

const compareRules = (a: RuleMeta, b: RuleMeta): number =>
  RULE_CATEGORIES.indexOf(a.category) - RULE_CATEGORIES.indexOf(b.category) || getCanonicalRuleId(a).localeCompare(getCanonicalRuleId(b));

const renderRow = (meta: RuleMeta): string =>
  `| \`${getCanonicalRuleId(meta)}\` | ${meta.category} | ${meta.defaultSeverity} | ${meta.confidence} | ${meta.frameworks.join(", ")} | ${meta.engine} |`;

export const renderRulesTable = (rules: readonly RuleMeta[] = RULE_REGISTRY): string =>
  [
    "<!-- Generated by packages/vue-doctor/scripts/generate-rules-table.ts. Do not edit; run `npm run rules:table`. -->",
    "",
    "| Rule | Category | Default severity | Confidence | Frameworks | Engine |",
    "|------|----------|------------------|------------|------------|--------|",
    ...[...rules].sort(compareRules).map(renderRow),
    "",
  ].join("\n");

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const next = renderRulesTable();
  const previous = fs.existsSync(RULES_TABLE_PATH) ? fs.readFileSync(RULES_TABLE_PATH, "utf8") : "";
  if (next !== previous) fs.writeFileSync(RULES_TABLE_PATH, next);
  console.log(`${next === previous ? "Up to date" : "Wrote"} ${path.relative(process.cwd(), RULES_TABLE_PATH)}`);
}
