// Generates src/plugin/rules/index.ts, the barrel that statically imports every rule.
//
// oxlint loads the plugin from a single bundle, so rules must be statically imported; a bundler
// cannot discover them by itself. Adding a rule is therefore: create
// src/plugin/rules/<category>/<rule-id>.ts (with `export default defineRule(...)`, or `defineFsRule(...)` for
// project-file rules, `defineAuditRule(...)` for the opt-in dependency audit), then run
// `npm run rules:generate`. tests/registry.test.ts fails when the barrel is out of date.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rulesDirectory = path.join(packageDirectory, "src", "plugin", "rules");
const barrelPath = path.join(rulesDirectory, "index.ts");

// Files inside a category folder that hold shared code rather than a rule. Colocated test data
// (`<rule-id>.cases.ts`, see src/plugin/rule-cases.ts) is skipped by suffix.
const NON_RULE_FILES = new Set(["helpers.ts"]);

const toIdentifier = (relativePath) =>
  relativePath
    .replace(/\.ts$/, "")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part, index) => (index === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");

/** Rule files as forward-slash paths relative to the rules directory, sorted for stable output. */
export const listRuleFiles = (directory = rulesDirectory) => {
  const files = [];
  for (const category of fs.readdirSync(directory, { withFileTypes: true })) {
    if (!category.isDirectory()) continue;
    for (const entry of fs.readdirSync(path.join(directory, category.name), { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".ts") || NON_RULE_FILES.has(entry.name)) continue;
      if (entry.name.endsWith(".cases.ts")) continue;
      files.push(`${category.name}/${entry.name}`);
    }
  }
  return files.sort();
};

export const renderBarrel = (directory = rulesDirectory) => {
  const files = listRuleFiles(directory);
  const imports = files.map(
    (file) => `import ${toIdentifier(file)} from "./${file.replace(/\.ts$/, ".js")}";`,
  );
  const entries = files.map((file) => `  ${toIdentifier(file)},`);
  return [
    "// Generated by scripts/generate-rules.mjs. Do not edit; run `npm run rules:generate`.",
    'import type { DefinedRule } from "../define-rule.js";',
    'import type { DefinedFsRule } from "../define-fs-rule.js";',
    'import type { DefinedAuditRule } from "../define-audit-rule.js";',
    ...imports,
    "",
    "export const ruleModules: readonly (DefinedRule | DefinedFsRule | DefinedAuditRule)[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");
};

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const next = renderBarrel();
  const previous = fs.existsSync(barrelPath) ? fs.readFileSync(barrelPath, "utf8") : "";
  if (next !== previous) fs.writeFileSync(barrelPath, next);
  console.log(`${next === previous ? "Up to date" : "Wrote"} ${path.relative(process.cwd(), barrelPath)}`);
}
