name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I expected X to happen, but Y happened instead.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Vue Doctor Version
      description: Which version of `@remylagerweij/vue-doctor` are you using? (e.g., 1.0.0)
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide code snippets or a link to a reproduction repository.
      placeholder: |
        1. Run `npx @remylagerweij/vue-doctor .`
        2. See error: ...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs or error output here.
      render: shell
