import type { RuleMeta } from "./define-rule.js";

/**
 * Metadata for the eslint-plugin-vue template rules Vue Doctor runs. They have no `create`: the
 * implementations live in eslint-plugin-vue, and the registry only needs their metadata to build
 * the ESLint config and to give template findings a category and help text.
 */
const templateRule = (meta: Omit<RuleMeta, "engine" | "fixable" | "since" | "frameworks">): RuleMeta => ({
  ...meta,
  frameworks: ["vue", "nuxt"],
  fixable: false,
  since: "1.0.0",
  engine: "eslint-template",
});

export const TEMPLATE_RULES: readonly RuleMeta[] = [
  templateRule({
    id: "vue/require-v-for-key",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Add a unique `:key` attribute to every `v-for` iteration element",
    agentGuidance: "Add a unique, stable `:key` to the element that has `v-for` (an id from the data, not the index).",
  }),
  templateRule({
    id: "vue/no-use-v-if-with-v-for",
    category: "Performance",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Move `v-if` to a wrapper element or use `computed` to filter the list",
    agentGuidance: "Do not put `v-if` and `v-for` on the same element. Filter the list in a `computed` and iterate the result, or move `v-if` to a wrapping `<template>`.",
  }),
  templateRule({
    id: "vue/no-template-shadow",
    category: "Correctness",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Rename the variable to avoid shadowing a component property",
    agentGuidance: "Rename the `v-for`/slot variable so it no longer shadows a prop, data or setup binding of the same name.",
  }),
  templateRule({
    id: "vue/valid-v-slot",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Use `v-slot` only on `<template>` elements or component direct children",
    agentGuidance: "Use `v-slot` (or `#`) only on `<template>` or on a component's direct slot, with a valid name and at most one default slot.",
  }),
  templateRule({
    id: "vue/require-explicit-emits",
    category: "Correctness",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Define emits with `defineEmits()` for better documentation and type checking",
    agentGuidance: "Declare every emitted event in `defineEmits()` (or the `emits` option) and use those names when emitting.",
  }),
  templateRule({
    id: "vue/component-name-in-template-casing",
    category: "Architecture",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Use PascalCase for component names in templates: `<MyComponent>`",
    agentGuidance: "Write component tags in PascalCase, for example `<MyComponent />`, instead of kebab-case or lowercase.",
  }),
  templateRule({
    id: "vue/no-unused-vars",
    category: "Dead Code",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Remove the unused variable or prefix with `_` to indicate intentional",
    agentGuidance: "Remove the unused `v-for`/slot-scope variable, or prefix it with an underscore if the position is required.",
  }),
  templateRule({
    id: "vue/no-mutating-props",
    category: "Reactivity",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Never modify a prop directly — emit an event to the parent instead",
    agentGuidance: "Never assign to a prop or mutate it in the template. Emit an event so the parent updates the value, or copy the prop into local state.",
  }),
  templateRule({
    id: "vue/no-computed-properties-in-data",
    category: "Reactivity",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Move the reference into `computed` or `setup()` instead of `data()`",
    agentGuidance: "Do not reference computed properties from `data()`; they are not ready yet. Derive the value inside a `computed` or `setup()` instead.",
  }),
  templateRule({
    id: "vue/no-side-effects-in-computed-properties",
    category: "Reactivity",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Computed properties must be pure — move side effects to `watch` or methods",
    agentGuidance: "Make the computed pure: move mutations and assignments to methods, watchers or event handlers.",
  }),
  templateRule({
    id: "vue/no-async-in-computed-properties",
    category: "Reactivity",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Use `watchEffect` or an async composable instead of async computed",
    agentGuidance: "Computed properties cannot be async. Use `watch`/`watchEffect` with a ref, or an async composable, and expose the result.",
  }),
  templateRule({
    id: "vue/return-in-computed-property",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Every computed property must return a value",
    agentGuidance: "Return a value on every code path of the computed getter.",
  }),
  templateRule({
    id: "vue/no-ref-as-operand",
    category: "Reactivity",
    defaultSeverity: "warning",
    confidence: "high",
    help: "Use `.value` to access the ref value in expressions",
    agentGuidance: "Access a ref's value through `.value` in script code (not in the template, where refs unwrap automatically).",
  }),
  templateRule({
    id: "vue/valid-v-bind",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Fix the `v-bind` / `:` directive syntax",
    agentGuidance: "Fix the `v-bind`/`:` syntax: it needs an argument or object, a non-empty value, and valid modifiers.",
  }),
  templateRule({
    id: "vue/valid-v-on",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Fix the `v-on` / `@` directive syntax",
    agentGuidance: "Fix the `v-on`/`@` syntax: it needs an event name and a valid handler expression or method.",
  }),
  templateRule({
    id: "vue/valid-v-model",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Fix the `v-model` directive — it must bind to a writable expression",
    agentGuidance: "Bind `v-model` to a writable variable or property; do not use it on a v-for alias, literal or computed expression.",
  }),
  templateRule({
    id: "vue/no-dupe-keys",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Remove the duplicate key — properties and computed names must be unique",
    agentGuidance: "Rename or remove the duplicate; props, data, computed and methods must not share names.",
  }),
  templateRule({
    id: "vue/no-duplicate-attributes",
    category: "Correctness",
    defaultSeverity: "error",
    confidence: "high",
    help: "Remove the duplicate attribute from the template tag",
    agentGuidance: "Remove the repeated attribute from the element; merge `class`/`style` values if both are needed.",
  }),
  templateRule({
    id: "vue/no-template-target-blank",
    category: "Security",
    defaultSeverity: "warning",
    confidence: "high",
    cwe: ["CWE-1022"],
    help: "Add `rel=\"noopener noreferrer\"` to links that use `target=\"_blank\"`",
    agentGuidance: "Add `rel=\"noopener noreferrer\"` to every link with `target=\"_blank\"`.",
  }),
];
