import fs from 'node:fs';
import path from 'node:path';

export interface WorkflowGeneratorOptions {
  failOn?: "error" | "warning" | "none";
  feedback?: string;
  grouping?: "finding" | "rule-per-file" | "rule";
  sarif?: boolean;
  audit?: boolean;
  agentPrompt?: boolean;
  forkComments?: boolean;
  defaultBranch?: string;
}

export const detectPackageManager = (projectDir: string): "npm" | "pnpm" | "yarn" | "bun" => {
  if (fs.existsSync(path.join(projectDir, "pnpm-lock.yaml"))) return "pnpm";
  if (fs.existsSync(path.join(projectDir, "yarn.lock"))) return "yarn";
  if (fs.existsSync(path.join(projectDir, "bun.lockb")) || fs.existsSync(path.join(projectDir, "bun.lock"))) return "bun";
  return "npm";
};

export const renderMainWorkflow = (options: WorkflowGeneratorOptions = {}): string => {
  const branch = options.defaultBranch ?? "main";
  const failOn = options.failOn ?? "error";
  const feedback = options.feedback ?? "summary,findings";
  const grouping = options.grouping ?? "rule-per-file";
  const agentPrompt = options.agentPrompt !== false;
  const sarif = options.sarif === true;
  const audit = options.audit === true;

  const permissions = [
    "  contents: read",
    "  pull-requests: write",
    "  checks: write",
    "  statuses: write",
  ];
  if (sarif) {
    permissions.push("  security-events: write");
  }

  const inputs = [
    `          fail-on: ${failOn}`,
    `          feedback: ${feedback}`,
    `          grouping: ${grouping}`,
    `          agent-prompt: ${agentPrompt}`,
  ];
  if (sarif) inputs.push("          sarif: true");
  if (audit) inputs.push("          audit: true");

  return `# Generated by vue-doctor ci install. Do not edit unless required.
name: Vue Doctor

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [${branch}]

permissions:
${permissions.join("\n")}

concurrency:
  group: vue-doctor-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  vue-doctor:
    name: Vue Doctor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Run Vue Doctor
        uses: remylagerweij/vue-doctor@v2
        with:
${inputs.join("\n")}
`;
};

export const renderForkCommentWorkflow = (): string => {
  return `# Generated by vue-doctor ci install --fork-comments.
# Runs with write permissions in response to the completed check without checking out fork code.
name: Vue Doctor Fork Comments

on:
  workflow_run:
    workflows: ["Vue Doctor"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  comment:
    name: Post PR Comments
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion != 'cancelled'
    steps:
      - name: Download scan results artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        with:
          name: vue-doctor-report
          run-id: \${{ github.event.workflow_run.id }}
          github-token: \${{ secrets.GITHUB_TOKEN }}

      - name: Post feedback
        uses: remylagerweij/vue-doctor@v2
        with:
          feedback-only: true
          report-json: vue-doctor.json
          github-token: \${{ secrets.GITHUB_TOKEN }}
`;
};
