// Generated by scripts/generate-rules.mjs. Do not edit; run `npm run rules:generate`.
import type { DefinedRule } from "../define-rule.js";
import type { DefinedFsRule } from "../define-fs-rule.js";
import type { DefinedAuditRule } from "../define-audit-rule.js";
import architectureNoGiantComponent from "./architecture/no-giant-component.js";
import architectureNoNestedComponentDefinition from "./architecture/no-nested-component-definition.js";
import bundleSizeNoBarrelImport from "./bundle-size/no-barrel-import.js";
import bundleSizeNoFullLodashImport from "./bundle-size/no-full-lodash-import.js";
import bundleSizeNoMoment from "./bundle-size/no-moment.js";
import bundleSizeNoUndeferredThirdParty from "./bundle-size/no-undeferred-third-party.js";
import bundleSizePreferDynamicImport from "./bundle-size/prefer-dynamic-import.js";
import correctnessNoArrayIndexAsKey from "./correctness/no-array-index-as-key.js";
import correctnessNoAsyncSetupWithoutSuspense from "./correctness/no-async-setup-without-suspense.js";
import correctnessNoDirectDomManipulation from "./correctness/no-direct-dom-manipulation.js";
import correctnessNoPreventDefault from "./correctness/no-prevent-default.js";
import correctnessNoThisInSetup from "./correctness/no-this-in-setup.js";
import correctnessPreferDefinePropsDestructure from "./correctness/prefer-defineProps-destructure.js";
import correctnessRequireDefinepropsTypes from "./correctness/require-defineprops-types.js";
import correctnessRequireEmitsDeclaration from "./correctness/require-emits-declaration.js";
import ecosystemPiniaNoDestructure from "./ecosystem/pinia-no-destructure.js";
import ecosystemPiniaNoWatchStore from "./ecosystem/pinia-no-watch-store.js";
import ecosystemRouterNoAsyncGuardWithoutNext from "./ecosystem/router-no-async-guard-without-next.js";
import ecosystemRouterNoStringPush from "./ecosystem/router-no-string-push.js";
import nuxtNoSecretInPublicRuntimeConfig from "./nuxt/no-secret-in-public-runtime-config.js";
import nuxtNoSensitivePublicFile from "./nuxt/no-sensitive-public-file.js";
import nuxtNuxtAsyncClientComponent from "./nuxt/nuxt-async-client-component.js";
import nuxtNuxtNoAElement from "./nuxt/nuxt-no-a-element.js";
import nuxtNuxtNoClientFetchForServerData from "./nuxt/nuxt-no-client-fetch-for-server-data.js";
import nuxtNuxtNoHeadImport from "./nuxt/nuxt-no-head-import.js";
import nuxtNuxtNoImgElement from "./nuxt/nuxt-no-img-element.js";
import nuxtNuxtNoProcessEnvInClient from "./nuxt/nuxt-no-process-env-in-client.js";
import nuxtNuxtNoWindowInSsr from "./nuxt/nuxt-no-window-in-ssr.js";
import nuxtNuxtRequireSeoMeta from "./nuxt/nuxt-require-seo-meta.js";
import nuxtNuxtRequireServerRouteErrorHandling from "./nuxt/nuxt-require-server-route-error-handling.js";
import nuxtSecurityHeaders from "./nuxt/security-headers.js";
import performanceAsyncParallel from "./performance/async-parallel.js";
import performanceClientPassiveEventListeners from "./performance/client-passive-event-listeners.js";
import performanceJsBatchDomCss from "./performance/js-batch-dom-css.js";
import performanceJsCacheStorage from "./performance/js-cache-storage.js";
import performanceJsCombineIterations from "./performance/js-combine-iterations.js";
import performanceJsEarlyExit from "./performance/js-early-exit.js";
import performanceJsHoistRegexp from "./performance/js-hoist-regexp.js";
import performanceJsIndexMaps from "./performance/js-index-maps.js";
import performanceJsMinMaxLoop from "./performance/js-min-max-loop.js";
import performanceJsSetMapLookups from "./performance/js-set-map-lookups.js";
import performanceJsTosortedImmutable from "./performance/js-tosorted-immutable.js";
import performanceNoDeepWatch from "./performance/no-deep-watch.js";
import performanceNoGlobalCssVariableAnimation from "./performance/no-global-css-variable-animation.js";
import performanceNoLargeAnimatedBlur from "./performance/no-large-animated-blur.js";
import performanceNoLayoutPropertyAnimation from "./performance/no-layout-property-animation.js";
import performanceNoPermanentWillChange from "./performance/no-permanent-will-change.js";
import performanceNoScaleFromZero from "./performance/no-scale-from-zero.js";
import performanceNoTransitionAll from "./performance/no-transition-all.js";
import reactivityNoCascadingMutations from "./reactivity/no-cascading-mutations.js";
import reactivityNoFetchInWatch from "./reactivity/no-fetch-in-watch.js";
import reactivityNoMissingAwaitNextTick from "./reactivity/no-missing-await-nextTick.js";
import reactivityNoMutationInComputed from "./reactivity/no-mutation-in-computed.js";
import reactivityNoReactiveDestructure from "./reactivity/no-reactive-destructure.js";
import reactivityNoReactiveReplace from "./reactivity/no-reactive-replace.js";
import reactivityNoRefFromProp from "./reactivity/no-ref-from-prop.js";
import reactivityNoWatchForComputed from "./reactivity/no-watch-for-computed.js";
import reactivityPreferComputed from "./reactivity/prefer-computed.js";
import securityLlmPromptInjection from "./security/llm-prompt-injection.js";
import securityNoCommittedEnv from "./security/no-committed-env.js";
import securityNoDynamicCode from "./security/no-dynamic-code.js";
import securityNoEval from "./security/no-eval.js";
import securityNoHardcodedSecret from "./security/no-hardcoded-secret.js";
import securityNoInjection from "./security/no-injection.js";
import securityNoJavascriptUrl from "./security/no-javascript-url.js";
import securityNoLlmSdkInClient from "./security/no-llm-sdk-in-client.js";
import securityNoOpenRedirect from "./security/no-open-redirect.js";
import securityNoPrototypePollution from "./security/no-prototype-pollution.js";
import securityNoSecretInPublicEnvFile from "./security/no-secret-in-public-env-file.js";
import securityNoSecretInPublicEnv from "./security/no-secret-in-public-env.js";
import securityNoSecretNamedLiteral from "./security/no-secret-named-literal.js";
import securityNoSsrf from "./security/no-ssrf.js";
import securityNoTokenInWebStorage from "./security/no-token-in-web-storage.js";
import securityNoUnsafeHtmlSink from "./security/no-unsafe-html-sink.js";
import securityNoUserControlledUrl from "./security/no-user-controlled-url.js";
import securityPostmessageOriginCheck from "./security/postmessage-origin-check.js";
import serverAuthMissing from "./server/auth-missing.js";
import serverCsrfOnMutatingRoutes from "./server/csrf-on-mutating-routes.js";
import serverRequireInputValidation from "./server/require-input-validation.js";
import serverSecureCookieFlags from "./server/secure-cookie-flags.js";
import serverServerNoConsoleInHandler from "./server/server-no-console-in-handler.js";
import supplyChainLockfileIntegrity from "./supply-chain/lockfile-integrity.js";
import supplyChainNoDependencyInstallScripts from "./supply-chain/no-dependency-install-scripts.js";
import supplyChainNoRemoteDependencySpec from "./supply-chain/no-remote-dependency-spec.js";
import supplyChainVulnerableDependency from "./supply-chain/vulnerable-dependency.js";

export const ruleModules: readonly (DefinedRule | DefinedFsRule | DefinedAuditRule)[] = [
  architectureNoGiantComponent,
  architectureNoNestedComponentDefinition,
  bundleSizeNoBarrelImport,
  bundleSizeNoFullLodashImport,
  bundleSizeNoMoment,
  bundleSizeNoUndeferredThirdParty,
  bundleSizePreferDynamicImport,
  correctnessNoArrayIndexAsKey,
  correctnessNoAsyncSetupWithoutSuspense,
  correctnessNoDirectDomManipulation,
  correctnessNoPreventDefault,
  correctnessNoThisInSetup,
  correctnessPreferDefinePropsDestructure,
  correctnessRequireDefinepropsTypes,
  correctnessRequireEmitsDeclaration,
  ecosystemPiniaNoDestructure,
  ecosystemPiniaNoWatchStore,
  ecosystemRouterNoAsyncGuardWithoutNext,
  ecosystemRouterNoStringPush,
  nuxtNoSecretInPublicRuntimeConfig,
  nuxtNoSensitivePublicFile,
  nuxtNuxtAsyncClientComponent,
  nuxtNuxtNoAElement,
  nuxtNuxtNoClientFetchForServerData,
  nuxtNuxtNoHeadImport,
  nuxtNuxtNoImgElement,
  nuxtNuxtNoProcessEnvInClient,
  nuxtNuxtNoWindowInSsr,
  nuxtNuxtRequireSeoMeta,
  nuxtNuxtRequireServerRouteErrorHandling,
  nuxtSecurityHeaders,
  performanceAsyncParallel,
  performanceClientPassiveEventListeners,
  performanceJsBatchDomCss,
  performanceJsCacheStorage,
  performanceJsCombineIterations,
  performanceJsEarlyExit,
  performanceJsHoistRegexp,
  performanceJsIndexMaps,
  performanceJsMinMaxLoop,
  performanceJsSetMapLookups,
  performanceJsTosortedImmutable,
  performanceNoDeepWatch,
  performanceNoGlobalCssVariableAnimation,
  performanceNoLargeAnimatedBlur,
  performanceNoLayoutPropertyAnimation,
  performanceNoPermanentWillChange,
  performanceNoScaleFromZero,
  performanceNoTransitionAll,
  reactivityNoCascadingMutations,
  reactivityNoFetchInWatch,
  reactivityNoMissingAwaitNextTick,
  reactivityNoMutationInComputed,
  reactivityNoReactiveDestructure,
  reactivityNoReactiveReplace,
  reactivityNoRefFromProp,
  reactivityNoWatchForComputed,
  reactivityPreferComputed,
  securityLlmPromptInjection,
  securityNoCommittedEnv,
  securityNoDynamicCode,
  securityNoEval,
  securityNoHardcodedSecret,
  securityNoInjection,
  securityNoJavascriptUrl,
  securityNoLlmSdkInClient,
  securityNoOpenRedirect,
  securityNoPrototypePollution,
  securityNoSecretInPublicEnvFile,
  securityNoSecretInPublicEnv,
  securityNoSecretNamedLiteral,
  securityNoSsrf,
  securityNoTokenInWebStorage,
  securityNoUnsafeHtmlSink,
  securityNoUserControlledUrl,
  securityPostmessageOriginCheck,
  serverAuthMissing,
  serverCsrfOnMutatingRoutes,
  serverRequireInputValidation,
  serverSecureCookieFlags,
  serverServerNoConsoleInHandler,
  supplyChainLockfileIntegrity,
  supplyChainNoDependencyInstallScripts,
  supplyChainNoRemoteDependencySpec,
  supplyChainVulnerableDependency,
];
